[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production" 